name: Lint

on: [push, pull_request]

env:  
  VAPOURSYNTH_VERSION: 71  
  PYTHON_VERSION: "3.13"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up VapourSynth ${{ env.VAPOURSYNTH_VERSION }}
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: ${{ env.VAPOURSYNTH_VERSION }}

      - name: Install dependencies
        run: |
          uv sync --locked

      - name: Running ruff
        run: |
          uv run ruff check .
          uv run ruff format --check --diff

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up VapourSynth ${{ env.VAPOURSYNTH_VERSION }}
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: ${{ env.VAPOURSYNTH_VERSION }}

      - name: Install dependencies
        run: |
          uv sync --locked

      - name: Running mypy
        run: uv run mypy vstransitions
