name: Publish releases to PyPI
on:
  push:
   tags:
      - v[0-9]+**

jobs:
    package_build:
      name: Build and push to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/vstransitions
      permissions:
        id-token: write
      steps:
      - uses: actions/checkout@v4

      - name: Prep Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Build
        run: uv build

      - name: Check the output
        run: uv run twine check --strict dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
