name: Publish releases to PyPI
on:
  push:
   tags:
      - v[0-9]+**

env:  
  VAPOURSYNTH_VERSION: 71  
  PYTHON_VERSION: "3.13"

jobs:
    package_build:
      name: Build and push to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/vstransitions
      permissions:
        id-token: write
      steps:
      - uses: actions/checkout@v4

      - name: Prep Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up VapourSynth ${{ env.VAPOURSYNTH_VERSION }}
        uses: ./.github/actions/setup-vapoursynth
        with:
          vapoursynth-version: ${{ env.VAPOURSYNTH_VERSION }}

      - name: Install dependencies
        run: uv sync --locked

      - name: Build
        run: uv build

      - name: Check the output
        run: uv run twine check --strict dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
